### PR TITLE
Show loading error messages on limit exception

### LINKED ISSUE #117: Strange LoadingLimitException case
With the following fixtures files:

```yml
AppBundle\Entity\Server:
    server (template):
        hostedDomain: sample.net
        mac: <macAddress()>
        sshUser: toor
        sshPort: 4242
        mysqlHost: localhost
        mysqlRoot: <password()>
        webServer: apache
        webServerSslListen: 0.0.0.0
        webServerSslPort: 443
        mysqlServer: true
        status: 1
        installedAt: <dateTime()>
    server_{1..9} (extends server):
        name: server_<current()>
```

I got the following error:

```bash
 [Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]                                                                                         
  Loading files limit of 5 reached. Could not load the following files: /home/sullivan/projects/project/src/AppBundle/DataFixtures/ORM/server.yml
```

And it works well if I remove this line:

```yml
        installedAt: <dateTime()>
```

I don't think this is the real error. I think upper exception is catched but no way to know what is happening.

Any solution for this?

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #117.

Sample output:

```
  [Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]                                                                 
  Loading files limit of 5 reached. Could not load the following files:                                                            
  /home/sullivan/projects/my/project/src/AppBundle/DataFixtures/ORM/ticket.yml:                                               
   - Entity with Id @user_support_14: and Class AppBundle\Entity\User not found                                                    
   - Entity with Id @user_support_19: and Class AppBundle\Entity\User not found                                                    
   - Entity with Id @user_support_20: and Class AppBundle\Entity\User not found                                                    
   - Entity with Id @user_support_7: and Class AppBundle\Entity\User not found                                                     
  /home/sullivan/projects/my/project/src/AppBundle/DataFixtures/ORM/cron.yml:                                                 
   - Instance mask "domain_*" did not match any existing instance, make sure the object is created after its references            
  /home/sullivan/projects/my/project/src/AppBundle/DataFixtures/ORM/server.yml:                                               
   - Instance mask "user_customer_42_*" did not match any existing instance, make sure the object is created after its references  
  /home/sullivan/projects/my/project/src/AppBundle/DataFixtures/ORM/domain.yml:                                               
   - Instance mask "server_*" did not match any existing instance, make sure the object is created after its references            
```

### CODE REVIEW

File: src/Alice/DataFixtures/LoadingLimitException.php [hunk 1]
```diff
@@ -33,10 +34,22 @@ public function __construct($limit, array $normalizedFixturesFiles)
...
-            'Loading files limit of %d reached. Could not load the following files: %s',
-            $limit,
-            implode(', ', $unloadedFiles)
-        );
+        $messageLines = [];
+        $messageLines[] = sprintf('Loading files limit of %d reached. Could not load the following files:', $limit);
+
+        sort($unloadedFiles);
+        foreach ($unloadedFiles as $unloadedFile) {
+            if (isset($errorMessages[$unloadedFile]) && count($errorMessages[$unloadedFile]) > 0) {
```
Comment (theofidry) [inline src/Alice/DataFixtures/LoadingLimitException.php]: use yoda conditions: `0 < count($errorMessages[$unloadedFile])`

Comment (Soullivaneuh) [inline src/Alice/DataFixtures/LoadingLimitException.php]: Yoda condition is for equal and different signs, not greater or lower.

Comment (Soullivaneuh) [inline src/Alice/DataFixtures/LoadingLimitException.php]: http://symfony.com/doc/current/contributing/code/standards.html#structure

File: tests/Alice/DataFixtures/LoaderTest.php [hunk 2]
```diff
@@ -231,4 +231,28 @@ public function testLoaderWithCustomLimit()
         $loader = new Loader($fixturesLoaderProphecy->reveal(), new ProcessorChain([]), false, 10);
         $loader->load($persisterProphecy->reveal(), ['random/file']);
     }
+
```
Comment (theofidry) [inline tests/Alice/DataFixtures/LoaderTest.php]: needs the `@cover` annotation

File: src/Alice/DataFixtures/Loader.php [hunk 3]
```diff
@@ -223,4 +228,23 @@ private function persist(PersisterInterface $persister, array $objects)
...
+
+    /**
+     * Registers the error message with the related fixture file.
+     *
+     * @param string $fixtureFilePath
+     * @param string $errorMessage
+     */
+    private function registerErrorMessage($fixtureFilePath, $errorMessage)
+    {
+        if (empty($errorMessage)) {
```
Comment (theofidry) [inline src/Alice/DataFixtures/Loader.php]: I agree it's not a big deal with `empty` and `is*, but I prefer to test it agains actual values, like here `if (true === empty($errorMessage))`. That's how it's been done in the whole library so let's stay consistant

File: src/Alice/DataFixtures/Loader.php [hunk 4]
```diff
@@ -45,6 +45,11 @@ class Loader implements LoaderInterface
     private $loadingLimit;
 
     /**
+     * @var string[]
+     */
+    private $errorMessages = [];
```
Comment (theofidry) [inline src/Alice/DataFixtures/Loader.php]: When is it actually reset? Shouldn't it be declared in the load function?

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 2 above)
Comment (Soullivaneuh) [inline tests/Alice/DataFixtures/LoaderTest.php]: I'm not used to use this annotation cause I think it could be erroneous.

BTW, the `@cover` method is no present on another exception tests.

If you want it, what should I put on this?

File: tests/Alice/DataFixtures/LoaderTest.php [hunk 5]
```diff
@@ -231,4 +231,28 @@ public function testLoaderWithCustomLimit()
...
+    public function testLoaderLimitWithMessages()
```
Comment (theofidry) [inline tests/Alice/DataFixtures/LoaderTest.php]: As always :+1: for tests, but I would add a second call to the test just to ensure the error messages are properly reset between each loading

Comment (Soullivaneuh) [inline tests/Alice/DataFixtures/LoaderTest.php]: I'm not sure to understand what you want exactly.

File: src/Alice/DataFixtures/LoadingLimitException.php (hunk 1 above)
Comment (theofidry) [inline src/Alice/DataFixtures/LoadingLimitException.php]: > In programming jargon, Yoda conditions (also called Yoda notation) is a programming style where the two parts of an expression are reversed from the typical order in a conditional statement.

True yoda conditions applies for everything and I kind of find it mess up to do only for half conditions and for the sake of consistancy let's stick to the true Yoda conditions (it's like that for the whole bundle so...)

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 2 above)
Comment (theofidry) [inline tests/Alice/DataFixtures/LoaderTest.php]: add it with the methods tested. The `@cover` is just to specify which functions are actually tested even if the test doesn't fully cover the function

**Comment by theofidry** [comment]
Good one, I like it :)

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 5 above)
Comment (theofidry) [inline tests/Alice/DataFixtures/LoaderTest.php]: What I want to ensure is that it goes as the following:

- run loading one time
- fail: get a message "message A"
- run loading one more time
- fail: get a message "message B"

And not:

- run loading one time
- fail: get a message "message A"
- run loading one more time
- fail: get a message "message A" + "message B"

File: src/Alice/DataFixtures/LoadingLimitException.php (hunk 1 above)
Comment (Soullivaneuh) [inline src/Alice/DataFixtures/LoadingLimitException.php]: Yeah but Symfony CS does not apply full yoda condition. :-)

As discussed on another thread, it's useful to avoid mistake with assignation (`=`) but change nothing for other operators.

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 2 above)
Comment (Soullivaneuh) [inline tests/Alice/DataFixtures/LoaderTest.php]: > add it with the methods tested.

Yeah, that's my question. Which ones?

> The `@cover` is just to specify which functions are actually tested even if the test doesn't fully cover the function

Yeah, this is exactly what I don't like... If I want, I can set `@cover toto` without test the toto method. I think it's lying IMO. :-)

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 5 above)
Comment (Soullivaneuh) [inline tests/Alice/DataFixtures/LoaderTest.php]: Oh I see, will try.

File: src/Alice/DataFixtures/LoadingLimitException.php (hunk 1 above)
Comment (theofidry) [inline src/Alice/DataFixtures/LoadingLimitException.php]: Oh yeah it doesn't have any practical value to force it to operators, but personally I find it inconvenient to have both conditions type at the same time.

>Yeah but Symfony CS does not apply full yoda condition. :-)

It should... we can open a ticket for that but otherwise it's not much of an issue atm.

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 5 above)
Comment (Soullivaneuh) [inline tests/Alice/DataFixtures/LoaderTest.php]: Hmm I don't know how to do.

I tested by calling $loader->load a second time with a setExpectedException with a wrong message, tests passes...

Any idea of how to apply this test?

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 2 above)
Comment (theofidry) [inline tests/Alice/DataFixtures/LoaderTest.php]: >Yeah, this is exactly what I don't like... If I want, I can set @cover toto without test the toto method. I think it's lying IMO. :-)

It's lying to the reader but fortunately the reader don't care because he will rely on the coverage report, for which it won't be a lie but just an information as which functions will be covered an prevent unintended coverage.

File: src/Alice/DataFixtures/LoadingLimitException.php (hunk 1 above)
Comment (Soullivaneuh) [inline src/Alice/DataFixtures/LoadingLimitException.php]: > It should...

Maybe (I not agree), but this is the Symfony CS rules. Should we follow them or do you want this yoda condition in any case?

> we can open a ticket for that

Already discussed and refused on php-cs-fixer AFAIK.

> I find it inconvenient to have both conditions type at the same time.

Well, tastes and colors... :-)

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 2 above)
Comment (Soullivaneuh) [inline tests/Alice/DataFixtures/LoaderTest.php]: > he will rely on the coverage report

You're telling me that `@cover` does not have influence to coverage files generation?

File: src/Alice/DataFixtures/LoadingLimitException.php (hunk 1 above)
Comment (theofidry) [inline src/Alice/DataFixtures/LoadingLimitException.php]: >Maybe (I not agree), but this is the Symfony CS rules. Should we follow them or do you want this yoda condition in any case?

I say "it should", in the sense that the Symfony Yoda is not the yoda so doesn't make sense to me not having only the Symfony one.

> we can open a ticket for that
Already discussed and refused on php-cs-fixer AFAIK.

Then so be it, I won't waste energy for that :/

>I find it inconvenient to have both conditions type at the same time.
Well, tastes and colors... :-)

*Choosing between yoda and non-yoda conditions* is more a question of tastes and colors. Having only one is more a practical question to me. When you're dead tired I like to help your brain by providing somethings he's used to. If you have the same convention everywhere you will never think twice about it.

File: tests/Alice/DataFixtures/LoaderTest.php (hunk 2 above)
Comment (theofidry) [inline tests/Alice/DataFixtures/LoaderTest.php]: >You're telling me that @cover does not have influence to coverage files generation?

It does, that's the point. If I have:

```php
function testSomething()
{
    // call ::functionA() and ::functionB()
}
```

It will add coverage for both `::functionA()` and `::functionB()`. But by adding `@cover ::functionA`, the coverage for `::functionB()` will be ignored.

File: src/Alice/DataFixtures/LoadingLimitException.php (hunk 1 above)
Comment (theofidry) [inline src/Alice/DataFixtures/LoadingLimitException.php]: From FriendsOfPHP/PHP-CS-Fixer#611 it looks like it does

Comment (Soullivaneuh) [inline src/Alice/DataFixtures/LoadingLimitException.php]: This version was removed: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/700

And I'm pretty sure they discussed about applies yoda only for == like symbols.

In any way, it's specified on the [Symfony CS standards](http://symfony.com/doc/current/contributing/code/standards.html#structure):

> this applies to ==, !=, ===, and !==

Comment (Soullivaneuh) [inline src/Alice/DataFixtures/LoadingLimitException.php]: See also https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/611#issuecomment-57337056.

File: src/Alice/DataFixtures/Loader.php (hunk 4 above)
Comment (Soullivaneuh) [inline src/Alice/DataFixtures/Loader.php]: I'll put it before the while start.

**Comment by Soullivaneuh** [comment]
@theofidry review fixed. :+1:

**Comment by theofidry** [comment]
Thank you @Soullivaneuh

**Comment by Soullivaneuh** [comment]
Hey @theofidry, could we have a stable release for this? Thanks!

**Comment by theofidry** [comment]
Here you go! [v1.1.0](https://github.com/hautelook/AliceBundle/releases/tag/v1.1.0). Sorry I'm not being very active right now very very busy days at work, hopefully it will get better in the coming weeks ;)

**Comment by Soullivaneuh** [comment]
:+1:
